require 'httparty'
require 'open-uri'
require 'nokogiri'
require 'launchy'
require 'readline'
require 'pry'
require './concerns/menu_mod'

require_relative  './coral_getter/version'
require_relative  '../concerns/menu_mod'
require_relative './coral_getter/scraper'
require_relative './coral_getter/cli'
require_relative './coral_getter/spscoral'
require_relative './coral_getter/end/end_class'
require_relative './coral_getter/fox/fox'
require_relative './coral_getter/coral_banner/coral_price'
